### ISSUE TITLE
how to open SpotlightDownloader.exe? where is it located?

### ISSUE THREAD

**Issue by PalashSachan** [ORelio/Spotlight-Downloader#1]
your software looks great and i want to download as many as spotlight wallpapers because i love them a lot..please help me in resolving these issues.

how to open SpotlightDownloader.exe? where is it located?

i have read the instructions and unable to find the exe file to run

I cannot find SpotlightDownloader.exe or SpotlightDL.exe in your project..there are only .cs c# code files

where is it and how to run it and download it

so please help

thanks 💯 🥇  👍

**Comment by ORelio** [comment]
Hi,

Thanks for your interest 🙂 

There is no exe file in the source code, they are located in the [releases](https://github.com/ORelio/Spotlight-Downloader/releases) section.

Happy using :wink:

**Comment by PalashSachan** [comment]
ohh..i did'nt see that..
thanks for reply and what a great software you have made..brilliant man 💯 hats off to you 🥇 
now i can very easily download windows spotlight wallpapers in one click

thanks 👍
