### ISSUE TITLE
locale list

### ISSUE THREAD

**Issue by Louvas** [ORelio/Spotlight-Downloader#11]
Hello @ORelio ,

As also related in issues #6 and #7, changing the locale to get more images was too much trouble since there are so many to choose from. I decide to test and try an extensive list of locales and see what works with Spotlight. I've added each of them as an extra command line inside the .bat file so every time it finishes to execute with one locale it goes to the next one and so on. Usually with the first pass it downloads +600 different images using the 318 different locales.

I've attached the list of locales I've being using (most likely all that Spotlight supports - give or take). Hopefully this information will help to implement them within the code as default, making it possible to download as much images as possible without the hassle to edit the batch file to add hundreds of extra command lines.

Thank you!

[locales.txt](https://github.com/ORelio/Spotlight-Downloader/files/4549039/locales.txt)

**Comment by ORelio** [comment]
Congrats for identifying the list of valid locales supported by the Spotlight API 👍

I'll try to add something like `--locale ALL` to collect images in all languages. The only issue I see with this approach would be metadata harvesting with `--metadata` that would collect image descriptions in random languages, that would be not very useful. Maybe Spotlight Downloader should display a warning if using `--locale ALL` in combination with `--metadata` 🤔

**Comment by ORelio** [comment]
This is now implemented as per release [v1.4.3](https://github.com/ORelio/Spotlight-Downloader/releases/tag/v1.4.3). Thanks 😉
