### ISSUE TITLE
Licence violation?

### ISSUE THREAD

**Issue by Rab-C** [ORelio/Spotlight-Downloader#13]
I don't know, maybe the author of the Windows Store app XSpot has been in touch with you & sorted something out. You are acknowledged in the app. 

But the licence notices seem to have been stripped out as part of wrapping a GUI around Spotlight-Downloader - I certainly can't find the relevant text anywhere in the app or appx bundle. So since people monetizing OS & licence-stripping in the process is a personal bugbear of mine, I thought I'd at least bring it up.

Cheers for the hard work - ironically now I've discovered the original this is what I'm using in preference to the paywall-hobbled Xspot app...

**Comment by ORelio** [comment]
Thanks for reporting this. I did not know about this app nor was in touch with the developer, but it seems to comply with the license. I have set a pretty permissive license for this project which allows commercial use as long as credit is properly given, which is the case here.

Strictly speaking, the author of XSpot must also distribute a copy of the code taken and modified from this repository - i.e. if they fix something - but not the GUI code which is not part of the original project. I see no major addition worth publishing besides the GUI so it should not make a big difference.

Anyway, as you noticed, SpotlightDL without a GUI is well enough to download Spotlight images 😄
