### ISSUE TITLE
How To ... 

### ISSUE THREAD

**Issue by SadSack963** [ORelio/Spotlight-Downloader#14]
Maybe it's just me being stupid. Please excuse my ignorance...

Your README says: 
"Simply call SpotlightDownloader.exe from the Windows command prompt"
However, there isn't an exe in the download.

I have VSCode and .NET Core SDK and C# Extension. I have never worked in any of these, I am a complete novice. I simply don't know how to build the project. Can you offer some tips please?

**Comment by ORelio** [comment]
See #1 seems like you're looking for the [releases](https://github.com/ORelio/Spotlight-Downloader/releases) section.

**Comment by SadSack963** [comment]
Thank you. How I missed that I don't know.
Still, any tips on how to build from source? I've tried dotnet build and got:
Build succeeded.
C:\Program Files\dotnet\sdk\3.1.301\NuGet.targets(128,5): warning : Unable to find a project to restore! [E:\GitHub Repositories\Spotlight-Downloader\SpotlightDownloader.sln]
    1 Warning(s)
then dotnet run
Couldn't find a project to run. Ensure a project exists in E:\GitHub Repositories\Spotlight-Downloader, or pass the path to the project using --project.

**Comment by ORelio** [comment]
Use `msbuild` with `SpotlightDownloader.csproj` or F6 in Visual Studio.
For more info, see [how to build from source](https://github.com/ORelio/Minecraft-Console-Client#building-from-source) from another project of mine.

**Comment by SadSack963** [comment]
Thank you for your help. I won't bother you further with noob questions. :)

**Comment by ORelio** [comment]
It's fine 😉
