### ISSUE TITLE
Add a folder with dates of download in /SpotlightArchive

### ISSUE THREAD

**Issue by potitpanda** [ORelio/Spotlight-Downloader#15]
Good morning 
Is it possible to add as feature , the automatic (or optional like "--day" in command line) creation of a folder with the date of the day when spotlightDL donwload new images ? So it can be more simple to sort new images than ancient when the content of /SpotlightArchive becomes big. 
Thanks
Potitpanda

**Comment by ORelio** [comment]
Hi @potitpanda, and welcome to GitHub!
How about setting `--outdir %date:/=-%` in your batch file? That would create a different folder each day.
```bat
mkdir %date:/=-% > nul 2>&1
SpotlightDownloader download --many --maxres --metadata --outdir %date:/=-%
```
Of course you can also use subfolders.
```bat
mkdir SpotlightArchive > nul 2>&1
mkdir SpotlightArchive\%date:/=-% > nul 2>&1
SpotlightDownloader download --many --maxres --metadata --outdir SpotlightArchive\%date:/=-%
```
If you just want to limit the amount of images, you can also limit the size of your archive with `--cache-size`.
This will automatically delete the oldest images when reaching the max size.

**Comment by potitpanda** [comment]
So i want to get in /SpotlightArchive/%date%/
ONLY newest images than /SpotLIghtArchive/
You understand it ?
Thanks

**Comment by potitpanda** [comment]
I Want to compare files by NAME not by date between /SpotlightArchive/ and
/SpotlightArchive/%+-date
So if 2 identical names was encountered, it deletes the file in
/SpotlightArchive/%+-date.
So in /SpotlightArchive/%+-date, it may have only NEWEST FILES...

**Comment by ORelio** [comment]
I see. In that case, that would conflict with the feature that checks if an image has already been downloaded. As a workaround, you can group by date in Windows explorer although that is not ideal... I'll leave the issue open in case I come up with a better solution.

**Comment by potitpanda** [comment]
That is not a conflict..... that is interesting....
If the program checks if an image is already downloaded the function to
create a folder with new images only was very interesting.
So i think the source of images was updated monthly.... not daily (try to
download images with ALL locales twice or three times.... your program
didn't download.... but with all locales, it download at once 590
images....)
So you should add a facultative feature to remove all the txt files at once.
So this is possible in  the batch file.

**Comment by potitpanda** [comment]
Sorry 490 pics at once yesterday and today !!!!! with No changes between
yesterday and today

**Comment by potitpanda** [comment]
...Sorry i can delete --metadata if i don't use txt files...

**Comment by potitpanda** [comment]
I Test a solution in batch files.... it will be good....

**Comment by potitpanda** [comment]
Using control of txt.... But it should go without this parameter...

**Comment by potitpanda** [comment]
@echo off
chcp 65001 > nul
title Réception des images dans Spotlight Archive et extraction des
nouveaux fichiers reçus dans Spotlight Archive uniquement dans un dossier
daté

cd "%~dp0"

:: This script downloads as much images as possible from the Spotlight API,
:: with maximum res and metadata. Please note that there is no actual way
:: of listing *all* images so SpotlightDownloader will make many API calls
:: to discover and download new images, and stop when no new images are
:: discovered. It may miss a few images but you should get most of them.

mkdir SpotlightArchive > nul 2>&1
SpotlightDownloader download --many --maxres --inconsistent-metadata
--all-locales --outdir SpotlightArchive

IF EXIST "%Userprofile%\Desktop\SpotDL\SpotlightArchive\*.txt" (
  mkdir %date:/=-%  >nul
robocopy c:\Users\PBPan\Desktop\SpotDL\SpotlightArchive\
c:\Users\PBPan\Desktop\SpotDL\%date:/=-%  *.jpg /DCOPY:T /XO
/maxage:%date:~6,4%%date:~3,2%%date:~0,2%
del %Userprofile%\Desktop\SpotDL\SpotlightArchive\*.txt > nul
@CLS
@Echo De nouveaux fichiers ont été ajoutés
Pause
exit
) ELSE (
@cls
echo Aucun nouveau fichier n'a été ajouté
pause
exit
)


Script is Working !
Adjust Robocopy
and the directories in the script.

**Comment by ORelio** [comment]
Indeed, if you don't delete images in the source directory that will work. Nice script 👍

**Comment by potitpanda** [comment]
Can you test and adjust parameters of Robocopy ?
Is this script can be adaptable as native exe ???

**Comment by potitpanda** [comment]
Je vais écrire en français :
J'ai crée un BATCH qui a la particularité d'appeler les locales les plus
"parlantes" (celles qui ont des fichiers a envoyer)
La particularité de ce fichier c'est que lorsque une série de "locales"
"parle", les métadonnées sont ensuite supprimées puis la même série est
intérrogée indéfiniment.
Ainsi cela permet de se retrouver avec plus de 600 images rapidement.
Si la série de locales parlantes ne parle plus.... on va interroger les
locales les moins bavardes par la suite selon le même principe.
Quand plus personne ne "parle" le batch s'arrete...
Mon problème est le suivant.
J'ai l'impression que plusieurs fichiers identiques sont téléchargés.
Comment "forcer le controle" de fichiers identiques et supprimer les
éventuels doublons ou empécher de télécharger 10 fois la même image,
sachant que je pense qu'il gardera le téléchargement d'une même image le
plus récent .???
Me fais-je comprendre ?
Bonne journée

**Comment by ORelio** [comment]
Hi,

_Il est d'usage d'utiliser l'Anglais sur GitHub. Je vais donc continuer en anglais.
It is a common practice to use English on GitHub, so I'll continue in english._

* If you plan to delete the `.txt` files after download then you can remove `--inconsistent-metadata` and `.txt` files will not be created at all by the program. So you won't need to delete them.

* When you use `--all-locales`, SpotlightDL will automatically attempt to download as many image as possible for each locale, then move on to the next locale. You should not need to do this in your Batch file.

* Regarding identical images: All images are named after the first half of its `sha256` checksum in the `UUID` format. So two identical images should have the same checksum and thus not be downloaded twice. Maybe the API has similar images, but in that case the program cannot identify them automatically.
    * The algorithm for downloading new images is roughly the following:
```
while new images are found:
    check if a file with the same name (checksum) already exists:
        if not, save the image under <checksum-uuid>.jpg
        otherwise, skip this image, it is not a new image
```
So if your images are placed in a different folder, the check for an existing image will not find it, and it will download it again.

**Comment by potitpanda** [comment]
If i don't delete the txt files, i can't see if new files was added... then
i can use robocopy to select the files by date.
I think every locale had a stock of images, so in each case if the locale
responding and send an image to my computer,  i loop  (or recall) the
"talking" locale
..... so ... can i with SpotlightDonwlader, increase the number of calls by
the program for each locale ?
So i use the batch files to download 600 pictures at once... (with the
loops of responding locales.)  i test this feature...

**Comment by potitpanda** [comment]
(or at twice, with slow locales... )

**Comment by ORelio** [comment]
Each time you call the API, it will return a random image. As there is no way of listing each image, SpotlightDL calls it again and again, and gives up after 50 unsuccessful calls (API returns an already downloaded image). This number is currently hardcoded. When using `--all-locales`, SpotlightDL moves on to the next locale after giving up for the previous locale, and so one. Of course you can call SpotlightDL several times to perform more tries on each locale.

**Comment by potitpanda** [comment]
So there's NOT  a random image......
i think all locales contains same images
today i use 30 locales to download 600 images...
All others locales not responding because it will dowload the same images
than my directory.
do you want my batch?

**Comment by ORelio** [comment]
Yes. Most locales have the same images with a different caption (translated to the associated locale). However, depending on the country, images may vary. Some locales are known to offer very few images, see #6. So `--all-locales` will just try every locale, see #11. If you already have a locale with many images such as `fr_FR` or `en_US`, trying all locales will not return much more images.

**Comment by potitpanda** [comment]
, trying all locales will not return much more images.
because All images are identical on each locales...
I have today 2 new images at the moment (i made some tests)
yesterday 8.....

**Comment by ORelio** [comment]
Yes. If you already have a locale with many images, trying all locales will not return much more images.

**Comment by potitpanda** [comment]
so your program can run with 31 locales . No much more !

**Comment by potitpanda** [comment]
the interrogation of 318 locales won't download much more 600 images at
twice.

**Comment by ORelio** [comment]
You can specify the locale you want with `--locale`, then call it once for each locale you want to use.

**Comment by potitpanda** [comment]
i don't want to call locale by locale...
i think you didn't understand what i mean.

**Comment by potitpanda** [comment]
i Want to call All images in once load....
i want to call only new images day by day....

**Comment by ORelio** [comment]
That is not possible because the Spotlight API returns one random image on each call and does not allow to specify anything else.
See for yourself: https://github.com/ORelio/Spotlight-Downloader#spotlight-api

**Comment by potitpanda** [comment]
I am sure that is not random images !!!
how many NEW images did you load today ? Me : 2

**Comment by potitpanda** [comment]
where can i send you my batch of "Locales parlantes" ?

**Comment by ORelio** [comment]
Microsoft maintains a pool of images on their side. When you call the API, you get one random image from their pool. On the initial load, you'll get most of them but not all due to the randomness of the API. When new images are added to the pool, old images are still there, so your chances of getting new images are slim. Additionally, I think that some images might also be removed from the pool on some occasions. You'll need to run the program regularly to get a few new images from time to time. 2 per day is normal.
