### ISSUE TITLE
Ignore a Locale 

### ISSUE THREAD

**Issue by potitpanda** [ORelio/Spotlight-Downloader#16]
Hello 
I Use SpotligtDownloader with -alllocales.... 
But : the locale 70 have a problem.  It doesn't work, retry and restart from locale 318 the program.  since 2 or 3 days
It won't continue 69... 68... 67 ... 66....
Any fix ???

**Comment by potitpanda** [comment]
Thanks...

**Comment by potitpanda** [comment]
Yes at the locale 70

**Comment by potitpanda** [comment]
In fact, it tries 3X and it reset at locale 318
i don't know the name of the locale ...
I will say you in few minutes....

SpotlightAPI: System.IO.InvalidDataException: SpotlightAPI: Missing
'batchrsp/items' field in JSON API response. Locale 'ms-MY' may be invalid.
- Waiting 10 seconds before retrying...
SpotlightAPI: System.IO.InvalidDataException: SpotlightAPI: Missing
'batchrsp/items' field in JSON API response. Locale 'ms-MY' may be invalid.
- Waiting 10 seconds before retrying...
System.IO.InvalidDataException: SpotlightAPI: Missing 'batchrsp/items'
field in JSON API response. Locale 'ms-MY' may be invalid.
Appuyez sur une touche pour continuer...

**Comment by potitpanda** [comment]
And the program didn't continue in reality it stops
The reset was caused by a loop i made in my script !

**Comment by ORelio** [comment]
Thanks for reporting. I could reproduce and fix your issue.


 - When an error occurs, download now properly resumes to the next locale
 - I removed ms-MY from the list

The fix will be included in next release. If you are unable to build the project yourself, here is a build with the fix:

* 📁 [SpotlightDL-v1.4.3-r1.zip](https://github.com/ORelio/Spotlight-Downloader/files/5010245/SpotlightDL-v1.4.3-r1.zip)

**Comment by potitpanda** [comment]
Thanks It Works
