### ISSUE TITLE
Locales for add in the program

### ISSUE THREAD

**Issue by potitpanda** [ORelio/Spotlight-Downloader#17]
Hello Here are some new locales i've tested and working based on a microsoft document

de-IT
en-AT
en-BI
en-CH 
en-CY
en-DE
en-HK
en-ID
en-NL 
en-SE 
en-SI 
es-BR 
es-BZ
fo-DR 
it-VA 
ku-IQ
lv-LT
mn-CN
ps-PK
pt-CH
pt-GQ
pt-LU 
sd-IN
sd-PK
sl-SL
sr-CS
sw-CD 
tk-TM
tn-BW 
wo-SN
zh-SG

I have a question 
Is it possible to remove the restriction of a locale called xx-YY please. 
So i have many locales to test 
Thanks

**Comment by potitpanda** [comment]
the locales aren't new but not in your locales list... So i made this add, this contribution

**Comment by ORelio** [comment]
Thanks. Added to the list. What format do you need? I can accommodate the restriction it there is some other local format.

**Comment by potitpanda** [comment]
I want no restrictions ! to test !

**Comment by potitpanda** [comment]
you can compile the program with the add of the locales
and made a compilation with no restrictions about the locales to test
and send me as an intermediate version

**Comment by potitpanda** [comment]
i don't know how to compile....

**Comment by potitpanda** [comment]
the format can be

xxx-YY as a leter
or
xx-YY letters (default)
or xx-000 so 000 are numbers

**Comment by potitpanda** [comment]
or only

xx  and xxx but i think the API send me an error

**Comment by ORelio** [comment]
Hi,
Of course, if you want to experiment, depending on your C# knowledge, it's faster to edit the source code and compile it yourself.
You can build the project with [Visual Studio](https://visualstudio.microsoft.com/vs/community/) or by following [these instructions](https://github.com/ORelio/Minecraft-Console-Client/#building-from-source) with `SpotlightDownloader.csproj`.
Here is a build with the latest locales you provided and without restriction on the `--locale` argument:
📁 [SpotlightDownloader.zip](https://github.com/ORelio/Spotlight-Downloader/files/5049848/SpotlightDownloader.zip)

**Comment by potitpanda** [comment]
GOOD
SO It WORKS

**Comment by potitpanda** [comment]
Hello I have a question
Why did you restrict initially the format of locales ?
I think this is a bad idea because.... this is a "technical point"... and
the lambda user didn't touch the locales.
I have tested some locales based on a list of microsoft LCIDs and many
works.

Here is my based document :
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f

Each locale contains 300 images. max. (i have tested all) .... with a few
little exceptions
Some locales when i send a looped ping didn't send 300 images quickly so
it can send  15 0 0 0 0 0 0 3 0 0 0 0 2 1 0 0 0 0 0 ...
Its probably the reason of no response of some locales... at the moment

So i have another idea.
In the program is it possible to verify and "Show" the presence of each
image;... If the image exists show "exists" and not OVERWRITE THE IMAGE.
(with use of a cache (???)
I think the program verify but didn't say "The image exists."
Thanks
