### ISSUE TITLE
Does Windows Spotlight have images for 4k displays?

### ISSUE THREAD

**Issue by Inetov** [ORelio/Spotlight-Downloader#19]
Am I correctly understand that there are no images larger than FullHD on Windows Spotlight servers?

If so your wonderful app is no longer relevant to me. You can close the #12 issue, if you want.
I got a new laptop with a 4k display and I don't like blurry images)

**Comment by ORelio** [comment]
I don't think so, since SpotlightDL with `--maxres` requests the API with a screen size of 99999 per 99999 pixels and still gets 1080p pictures. However I never tried the stock Spotlight lockscreen on a Windows 10 PC with a 4K display to make sure of this.

**Comment by chuck-stein** [comment]
@ORelio I have a 1440p monitor and the stock lock screen images have always appeared at native resolution. I wonder how these are downloaded from the API then, if the API seems to max out at 1080p? It seems to me there must be a way.
