### ISSUE TITLE
Portrait format for smartphone

### ISSUE THREAD

**Issue by Pokerness** [ORelio/Spotlight-Downloader#20]
Hi, 
In the w10 asset directory, we can see that each Spotlight image exists in 2 formats : landscape and portrait.  

Could it be possible to capture the two formats by adding an argument to choice the format : landscape, portrait or both, Two Archive directories should be required.

Thanks a lot for this great apps !

**Comment by ORelio** [comment]
Hi,

Currently, there is not support for downloading both images at the same time but you can use the `--portrait` parameter to get for portrait images. By default, Spotlight Downloader picks the appropriate image type from your main monitor's layout.

Also, correct me if I'm wrong but I think that portrait images are generated by cropping the landscape one so you can basically just define the landscape image as wallpaper on your smartphone and get the same result.

**Comment by Pokerness** [comment]
Hi,

Thanks a lot for your answer. That works well by combining --portrait --maxres parameters.

Portrait images are not a cropped landscape version because they have the same resolution 1080x1920, and it seems that they are not zoomed from a 610x1080 resolution.

**Comment by ORelio** [comment]
Good to know, glad that it works for you 👍
