### ISSUE TITLE
Download Data stage results in connection termination

### ISSUE THREAD

**Issue by starfireprime** [ORelio/Spotlight-Downloader#22]
I  found that Spotlight Downloader would fail upon trying to connect to the Spotlight API via https.  I believe this is due to the servers requiring TLS 1.2.  

I added the following at line 50 of Spotlight.cs

`System.Net.ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072; `

just prior to the call to webClient.DownloadData(request); .  That did the trick and files were properly returned.

**Comment by starfireprime** [comment]
Alternatively, just build for .NET 4.7.

**Comment by ORelio** [comment]
Hi @starfireprime thanks for reporting this issue and investigating the root cause.
Just released a new version including your fix 👍
