### ISSUE TITLE
Spotlight Downloader without restriction xx-YY on locale

### ISSUE THREAD

**Issue by potitpanda** [ORelio/Spotlight-Downloader#23]
Hi Orelio 
Could you send me a new version of SpotlightDownloader without restrictions in locales ? 
This is most powerful in order to download new images 
Thanks 
PS : You can eliminate this restriction in the others versions.  
Many Thanks 
PotitPanda

**Comment by ORelio** [comment]
Here is the requested build: 📁 [SpotlightDownloader.zip](https://github.com/ORelio/Spotlight-Downloader/files/6468080/SpotlightDownloader.zip)

**Comment by potitpanda** [comment]
Not Working ....

**Comment by ORelio** [comment]
As requested, the modified build allows you to use arbitrary locales and still works for locales known to work.
```
> SpotlightDownloader.exe urls --locale fr-FR
https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4IeBg?ver=a95c

> SpotlightDownloader.exe urls --locale aaa
--locale expected format is xx-XX, e.g. en-US. Locale 'aaa' might not work.
SpotlightAPI: System.IO.InvalidDataException: SpotlightAPI: Missing 'batchrsp/items' field in JSON API response. Locale 'aaa' may be invalid. - Waiting 10 seconds before retrying...
```
Of course, if the locale is invalid, you won't get anything. All locales I'm aware of were already allowed.

**Comment by ORelio** [comment]
I don't understand. Two-letters locales work:
```
> SpotlightDownloader.exe urls --locale fr
--locale expected format is xx-XX, e.g. en-US. Locale 'fr' might not work.
https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RWwzKl?ver=65bc
```
Please provide output of what you are trying to do.

**Comment by potitpanda** [comment]
I want to use --locale fr or --locale en
In a previous version you have done only for me it works... (but the
ancient url didn't work)

**Comment by ORelio** [comment]
As shown in my message above, you can use `--locale fr` with the modified build. And future versions will also have this change.

**Comment by potitpanda** [comment]
This is not working, no changes
Could you modify and rebuild the spotlightdownloader.exe
Thanks
P

**Comment by ORelio** [comment]
Please provide the exact command line you are typing and a screenshot or copy of the output.

**Comment by potitpanda** [comment]
The command is:

SpotlightDownloader download --many --maxres --inconsistent-metadata
--locale af --outdir SpotlightArchive
 --locale expected format is xx-XX, e.g. en-US. Locale 'af' might not
work.

SpotlightDownloader download --many --maxres --inconsistent-metadata
--locale am --outdir SpotlightArchive
--locale expected format is xx-XX, e.g. en-US. Locale 'am' might not work.
(...)

SpotlightDownloader download --many --maxres --inconsistent-metadata
--locale fr --outdir SpotlightArchive
  --locale expected format is xx-XX, e.g. en-US. Locale 'fr' might not
work.

There is always the restriction.

**Comment by ORelio** [comment]
This is a warning message, not an error. The program will proceed even if you see the warning.

**Comment by potitpanda** [comment]
I'm not really sure ...
In the previous version "for me", they haven't  the message.

**Comment by ORelio** [comment]
Yes, it did not. But now it does. Just have a look at the commit: https://github.com/ORelio/Spotlight-Downloader/commit/2159a22649cefb27f6c263dc8b6baa4ef01ec99b

**Comment by potitpanda** [comment]
Sorry that's OK
