### ISSUE TITLE
SpotlightAPI: System.ArgumentException: Customized cultures cannot be passed by LCID, only by name - error

### ISSUE THREAD

**Issue by Zoomer1988** [ORelio/Spotlight-Downloader#27]
Hi! 
I wanted to try Spotlight Downloader but I'm getting this error running any of the scripts or calling the exe file with Download parameter:
SpotlightAPI: System.ArgumentException: Customized cultures cannot be passed by LCID, only by name.
Parameter name: culture - Waiting 10 seconds before retrying...

Googling it leads to some Visual Studio update error where it has something to do with locales.

My system locale is English-US and my regional format is English (Europe) (never could get accustomed myself to yy/mm/dd format). Could this be due to this discrepancy?

**Comment by ORelio** [comment]
> My system locale is English-US and my regional format is English (Europe) (never could get accustomed myself to yy/mm/dd format). Could this be due to this discrepancy?

Yes, I think so. Try to edit the script you want to use and add `--locale en-US` to the SpotlightDL command.

**Comment by Zoomer1988** [comment]
Just tried running it as "spotlightdownloader download --locale en-US" from the command prompt - it unfortunately haven't changed anything. :(

**Comment by ORelio** [comment]
OK, I think I found the line that pose an issue:
https://github.com/ORelio/Spotlight-Downloader/blob/da817f9d501773eb928e0f0eb1084ca03bd7b9e7/SpotlightDownloader/Spotlight.cs#L30
When calling the API, there's a `locale` but also a `region`. The region is still automatically determined even when setting a locale. I'll look into a way of fixing that, meanwhile you can try changing regional format, that'll definitely work.

**Comment by ORelio** [comment]
Please try the following build without changing regional format and let me know if it works:
:open_file_folder: [SpotlightDownloader.zip](https://github.com/ORelio/Spotlight-Downloader/files/6865423/SpotlightDownloader.zip)
This should resolve the issue reported in your error message.

**Comment by Zoomer1988** [comment]
Yes, it works! No error messages, images downloaded correctly. Haven't had the time to change regional settings yesterday. Checked this thread and noticed your message. 

So currently it works with en-US locale and English (Europe) regional format.
Thank you very much!

**Comment by ORelio** [comment]
Thanks for posting a detailed bug report with exact error message and suggestion about the root cause.
Since you confirm it works, I've included the fix in the repository so that future releases will include it 😉

**Comment by xperiandri** [comment]
@ORelio, thank you for solution snippet!
