### ISSUE TITLE
auto save function

### ISSUE THREAD

**Issue by mxhx** [ORelio/Spotlight-Downloader#3]
Dear sir，can I save the image to my disk, maybe you can add the autosave function.

**Comment by ORelio** [comment]
I'm not sure to understand your issue. Spotlight Downloader has been specifically designed to download Spotlight images and save them to your disk. Use the provided `spotlight-download` script that comes in the same Zip file as SpotlightDL from the [releases](https://github.com/ORelio/Spotlight-Downloader/releases) section to download Spotlight images.

**Comment by ORelio** [comment]
As a reponse has been provided, I'll close this issue. Feel free to reopen if you still need help.
