### ISSUE TITLE
Linux/MacOS usage instructions

### ISSUE THREAD

**Issue by theofficialgman** [ORelio/Spotlight-Downloader#31]
The readme refers to `(Windows/Mac/Linux)` for usage but the releases only provide a windows executable file (.exe) and zip windows script language files which cannot run natively on Linux/MacOS. What was your intended method for running this application on MacOS and Linux?

**Comment by ORelio** [comment]
Hi,
You can run the .NET assembly (.exe) using Mono, the same way you can run a .jar using Java:
```
sudo apt install mono-runtime
mono SpotlightDownloader.exe
```
Adding this to the README, thanks for pointing out that instructions were lacking.

**Comment by ORelio** [comment]
Oh, also, you can look into the `.bat` scripts to see command examples, e.g. adapting from `spotlight-download-archive.bat`:
```bash 
mkdir SpotlightArchive
mono SpotlightDownloader download --many --maxres --metadata --outdir SpotlightArchive
```

**Comment by theofficialgman** [comment]
Thanks but I went ahead and just implemented the api scrap with curl and some simple sed commands for my needs. No need for anything more complicated that that for me.

**Comment by ORelio** [comment]
Well, the API documentation is here for that. Feel free to implement your own tools! 👍
