### ISSUE TITLE
API v4 (Win 11) returning an error

### ISSUE THREAD

**Issue by James-Oakley** [ORelio/Spotlight-Downloader#32]
Thanks for sharing this code.

The API v3 for Win 10 works fine.

But if I try the sample URL for v4 in the API documentation page, I get an error. I'd guess the endpoint has changed again their end.

```
# curl "https://fd.api.iris.microsoft.com/v4/api/selection?&placement=88000820&bcnt=4&country=US&locale=en-US&fmt=json"
{"batchrsp":{"ver":"1.0","errors":[{"code":2000,"msg":"No ad available. No additional information"}]}}
```

**Comment by ORelio** [comment]
Seems like they blocked curl. Add `-A "Mozilla/5.0"` (or literally any [user agent](https://www.useragents.me/#most-common-desktop-useragents) that does not contain the string "curl") to your command.

**Comment by James-Oakley** [comment]
> Seems like they blocked curl. Add `-A "Mozilla/5.0"` (or literally any [user agent](https://www.useragents.me/#most-common-desktop-useragents) that does not contain the string "curl") to your command.

Thanks, that was a fast reply, and fixed it straight off.

**Comment by ORelio** [comment]
Added a note about this in API documentation.
