### ISSUE TITLE
Check for metered connection is used

### ISSUE THREAD

**Issue by Inetov** [ORelio/Spotlight-Downloader#8]
Very useful application! But I have often work on mobile network and Windows cmd not provide any easy way to determine which connection is used: metered or not.
So I can't check it in .bat file.
Maybe you can implement this check in your application?

**Comment by ORelio** [comment]
Good idea. I'll check how to do this from a console application because officially only UWP applications have the relevant APIs for that.

**Comment by ORelio** [comment]
Implemented in release [1.4.2](https://github.com/ORelio/Spotlight-Downloader/releases/tag/v1.4.2) 😉

**Comment by Inetov** [comment]
thank you very much! nice solution without UWP!
